# Generated by Django 6.0.7 on 2026-07-09 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='related_asset',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='is_internal_note',
        ),
        migrations.AddField(
            model_name='ticket',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='computer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(choices=[('Production Floor', 'Production Floor'), ('Warehouse', 'Warehouse'), ('Finance', 'Finance'), ('HR', 'HR'), ('Sales', 'Sales'), ('Reception', 'Reception'), ('IT Office', 'IT Office'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Visible only to technicians'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('printing', 'Printing'), ('audio', 'Audio'), ('scanning', 'Scanning'), ('outlook_password', 'Outlook Password'), ('outlook_account', 'Outlook Account'), ('slack', 'Slack'), ('wifi', 'Wi-Fi'), ('network', 'Network'), ('software', 'Software'), ('hardware', 'Hardware'), ('laptop', 'Laptop'), ('phone', 'Phone'), ('email', 'Email'), ('access_request', 'Access Request'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
