# Generated by Django 6.0.7 on 2026-07-09 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_related_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('Finance', 'Finance'), ('HR', 'HR'), ('Production', 'Production'), ('Sales', 'Sales'), ('Warehouse', 'Warehouse'), ('Procurement', 'Procurement'), ('Reception', 'Reception'), ('IT', 'IT'), ('Other', 'Other')], default='Other', max_length=40),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='icon',
            field=models.CharField(default='laptop', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Printing', 'Printing'), ('Scanning', 'Scanning'), ('Outlook Password', 'Outlook Password'), ('Outlook Account', 'Outlook Account'), ('Email', 'Email'), ('Network', 'Network'), ('Wi-Fi', 'Wi-Fi'), ('Internet', 'Internet'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Phone', 'Phone'), ('Slack', 'Slack'), ('Microsoft Teams', 'Microsoft Teams'), ('Office 365', 'Office 365'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
