# Generated by Django 6.0.7 on 2026-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_asset_serial_number_ticket_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Accounts', 'Accounts'), ('Printing', 'Printing'), ('Network', 'Network'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Email', 'Email'), ('Phones', 'Phones'), ('Security', 'Security'), ('General', 'General')], max_length=30)),
                ('summary', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
