# Generated by Django 6.0.7 on 2026-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_knowledgebasearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
