# Generated by Django 6.0.7 on 2026-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_knowledgebasearticle_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('Finance', 'Finance'), ('HR', 'HR'), ('debt', 'debt'), ('Sales', 'Sales'), ('management', 'management'), ('marketing', 'marketing'), ('IT', 'IT'), ('ADMIN', 'ADMIN'), ('Other', 'Other')], default='Other', max_length=40),
        ),
    ]
