# Generated by Django 6.0.7 on 2026-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('finance', 'Finance'), ('management', 'Management'), ('marketing', 'Marketing'), ('admin', 'Admin'), ('sales', 'Sales'), ('debt', 'Debt Collection'), ('hr', 'Human Resources'), ('it', 'IT'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
