# Generated by Django 6.0.7 on 2026-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('employee', 'Employee'), ('technician', 'Technician')], default='employee', max_length=20),
        ),
    ]
