# Generated by Django 6.0.7 on 2026-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_notification_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='closed_at',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
    ]
